### ISSUE TITLE
Team09 Review: Traceable Requirements Table/Diagram

### ISSUE THREAD

**Issue by aaronhsli** [mehtaj8/Greenway#23]
One thing that would be a good addition according to the SRS rubric are tables/diagrams for your requirements. Your FRs and NFRs are all labelled well but there's no diagrams or tables provided to show the traceability. 

Aside: I think your Table of Contents is now missing after the latest commit per the image below. 
![image](https://user-images.githubusercontent.com/58313755/194731936-20d92516-61a4-4460-9e9f-c2ae46f1a96d.png)

**Comment by aaronhsli** [comment]
@nickcapstone

**Comment by Utsharga** [comment]
The document has been updated to reflect the changes.
