### ISSUE TITLE
Team 5 Review: Descriptive Test IDs

### ISSUE THREAD

**Issue by NevoAbigail** [mehtaj8/Greenway#80]
Test IDs are labelled according to section, but not descriptive further than that--test IDs could be labelled such that the reader has a rough idea of what exactly the test is testing.

Team 5 TA: @NickCapstone

**Comment by Utsharga** [comment]
Thank you for the suggestion. The team has gone forward with using these test IDs as a reference to the test cases. The test cases themselves are very descriptive.
