### ISSUE TITLE
Review-VnVRep-Team32: Adding feedback from Rev 0 demo

### ISSUE THREAD

**Issue by YiweiHe** [mehtaj8/Greenway#90]
You should consider documenting changes that were made based on the Rev 0 demo feedback. It is advised to document all changes and outlining the reason for the modification.

**Comment by Utsharga** [comment]
Thank you for the suggestion. Most of our stakeholders concerns and feedback were already noted in the future development and hence the team decided to not note it again with a commit/push change.
