### ISSUE TITLE
Team 5 Review: Control of initial states

### ISSUE THREAD

**Issue by AnthonyShenoud** [mehtaj8/Greenway#91]
Overall great layout and work some far. For preliminary requirement #3. I would add an initial state to incase any issues to arise you could have a default so the program does not crash. I'd like to keep this in mind for your other requirements. I believe it is good practice to always set a default in your development. Otherwise good luck :) 

Team 5 TA: @NickCapstone

**Comment by Utsharga** [comment]
Thank you for the suggestion. Current flow of the Car Model starts at state 0, i.e. no car model. The state once changed remains there as a usability feature for the user, i.e. the user does not have to start if scratch if they make a mistake. This encourages user learning and correction. and hence the team believes would not cause frustration for any of the users.
