### ISSUE TITLE
Team 5 Review - VnV Report: Optimizing

### ISSUE THREAD

**Issue by stephendejong** [mehtaj8/Greenway#92]
I found that this document was very thought out and tests had good procedures and were meaningful.
3.3 Backend Processing
      Backend Tests
      1. backend-test-1
            How will you be sure that the most optimal route has been found? You mention that if it produces a route with less fuel costs it passes however does this ensure that the code is finding the optimal code.
            Will you verify this optimization your self or with an external source like google maps etc..?

**Comment by Utsharga** [comment]
Yes, we have verified this test with an external source. We are already using Google MAP API for our mapping system, and hence have integrated settings to select optimal routes.
