### ISSUE TITLE
Team 5 Review - VnV: UI Accessibility Test Case

### ISSUE THREAD

**Issue by abdulriq** [mehtaj8/Greenway#93]
Overall the document was very well laid out and organized. I especially appreciated the inclusion of a few legal test cases when it comes to the use of APIs, that shows a forward thinking mindset of the team.

1. test-ui-1
How does the team plan on ensuring accessibility along with having a minimal UI? Accessibility is important especially in the user conditions that your service will be used in (for e.g while driving). I would recommend including a test case that measure the time and button presses it takes from start to finish, and see if there's room for improvement there. Other than that everything looks good, best of luck!

**Comment by Utsharga** [comment]
The team believes that minimal UI comes with accessibility. One major concern we tackled is accessibility with users who have visual impairments or are color blindness.

Our minimal UI proved through user survey that the color scheme was easily differentiated by users who have visual impairments or are color blindness.
